const dataProducts = [
        { 
            "id" : 1,
            "ProductName" :"Brokoli",
            "price" : 16000,
            "image" :  "https://images.unsplash.com/photo-1615485291234-9d694218aeb3?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "sayuran",
            "stock" : 30,
            "description" : "Brokoli adalah sayuran yang kaya akan nutrisi dan serat. Cocok untuk dipadukan dalam berbagai hidangan.",
        },
        { 
            "id" : 2,
            "ProductName" :"Jagung",
            "price" : 12000,
            "image" :  "https://images.unsplash.com/photo-1615485290161-7eb49a34eba5?q=80&w=871&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "sayuran",
            "stock": 10,
            "description" : "Jagung adalah sumber karbohidrat yang lezat dan sering dijadikan sebagai camilan. Kaya akan serat dan vitamin.",
        },
        { 
            "id" : 3,
            "ProductName" :"Terong",
            "price" : 10000,
            "image" :  "https://images.unsplash.com/photo-1615484477201-9f4953340fab?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "sayuran",
            "stock": 15,
            "description" : "Terong adalah sayuran berwarna ungu yang sering digunakan dalam berbagai masakan. Kaya akan antioksidan dan rendah kalori.",
        },
        { 
            "id" : 4,
            "ProductName" :"Sayur Kol",
            "price" : 8000,
            "image" :  "https://images.unsplash.com/photo-1583116935756-f66cd999cdbe?q=80&w=580&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "sayuran",
            "stock": 20,
            "description" : "Sayur Kol adalah sayuran yang kaya akan vitamin C dan serat. Cocok untuk dijadikan lauk atau tambahan dalam salad.",
        },
        { 
            "id" : 5,
            "ProductName" :"Bawang",
            "price" : 8000,
            "image" :  "https://images.unsplash.com/photo-1587049633312-d628ae50a8ae?q=80&w=1480&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "sayuran",
            "stock": 10,
            "description" : "Bawang adalah bumbu dapur yang umum digunakan dalam berbagai masakan. Kaya akan antioksidan dan memberikan aroma khas.",
        },
        { 
            "id" : 6,
            "ProductName" :"Anggur Segar",
            "price" : 8000,
            "image" :  "https://images.unsplash.com/photo-1615485925763-86786288908a?q=80&w=580&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "buah",
            "stock": 5,
            "description" : "Anggur Segar adalah buah yang lezat dan sering dijadikan camilan. Kaya akan antioksidan dan sering digunakan untuk membuat minuman.",
        },
        { 
            "id" : 7,
            "ProductName" :"Apel",
            "price" : 14000,
            "image" :  "https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "buah",
            "stock": 25,
            "description" : "Apel adalah buah yang segar dan menyehatkan. Kaya akan serat dan vitamin C, cocok untuk dikonsumsi sebagai camilan.",
        },
        { 
            "id" : 8,
            "ProductName" :"Pisang",
            "price" : 8000,
            "image" :  "https://images.unsplash.com/photo-1587334206596-c0f9f7dccbe6?q=80&w=581&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "buah",
            "stock": 30,
            "description" : "Pisang adalah buah yang kaya akan kalium dan serat. Cocok untuk dikonsumsi sebagai camilan atau dicampur dalam berbagai hidangan.",
        },
        { 
            "id" : 9,
            "ProductName" :"Pear",
            "price" : 9000,
            "image" :  "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?q=80&w=435&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "buah",
            "stock": 10,
            "description" : "Pear adalah buah yang memiliki rasa manis dan lembut. Kaya akan serat dan vitamin C, cocok untuk dikonsumsi sebagai camilan sehat.",
        },
        { 
            "id" : 10,
            "ProductName" :"Wortel",
            "price" : 12000,
            "image" :  "https://images.unsplash.com/photo-1576181256399-834e3b3a49bf?q=80&w=1475&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "sayuran",
            "stock": 18,
            "description" : "Wortel adalah sayuran berwarna oranye yang kaya akan beta-karoten. Baik untuk kesehatan mata dan sistem kekebalan tubuh.",
        },
        { 
            "id" : 11,
            "ProductName" :"Jeruk",
            "price" : 16000,
            "image" :  "https://images.unsplash.com/photo-1587334207477-cb3e3ff0637f?q=80&w=1480&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "buah",
            "stock": 25,
            "description" : "Jeruk adalah buah yang kaya akan vitamin C dan antioksidan. Baik untuk menjaga kesehatan kulit dan sistem pencernaan.",
        },
        { 
            "id" : 12,
            "ProductName" :"Cherry",
            "price" : 26000,
            "image" :  "https://images.unsplash.com/photo-1528821128474-27f963b062bf?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "category" : "buah",
            "stock": 8,
            "description" : "Cherry adalah buah kecil berwarna merah yang kaya akan antioksidan. Cocok untuk dimakan langsung atau sebagai tambahan dalam berbagai hidangan.",
        },
        
]

export default dataProducts ;